package com.bbva.net.consulta.cifin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2016-12-26T14:27:14.513-05:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://www.bbvanet.com.co/ContratacionDigitalTX/", name = "ContratacionDigitalTX")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratacionDigitalTX {

    @WebResult(name = "CONSULTACOMERCIALRESPONSE", targetNamespace = "http://www.bbvanet.com.co/ContratacionDigitalTX/", partName = "parameters")
    @WebMethod(action = "http://www.bbvanet.com.co/ContratacionDigitalTX/consultaComercial")
    public ValidarConsultaResponseType consultaComercial(
            @WebParam(partName = "parameters", name = "CONSULTACOMERCIAL", targetNamespace = "http://www.bbvanet.com.co/ContratacionDigitalTX/")
                    ValidarConsultaType parameters
    );
}
